## Load Library Numpy

In [1]:
import numpy as np

# **Numpy Operation**

In [2]:
my_list = [1,2,3,4]

In [3]:
numpy_list = np.array(my_list)

In [4]:
numpy_list

array([1, 2, 3, 4])

In [5]:
'''Inisialisasi value pada numpy'''
zeros_np = np.zeros(5)
zeros_np

array([0., 0., 0., 0., 0.])

In [6]:
'''Multidimensional Array'''
numpy_multi = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [10]:
numpy_multi

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [11]:
numpy_multi.shape

(2, 5)

In [15]:
arr_A = np.array([1,2,3,4,5])
arr_A[2:]

array([3, 4, 5])

In [16]:
arr_B = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr_B[1,1]

7

In [17]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([6,7,8,9,0])

In [19]:
print('Penjumlahan', arr_A, 'dan', arr_B, '=', arr_A + arr_B)

Penjumlahan [1 2 3 4 5] dan [6 7 8 9 0] = [ 7  9 11 13  5]

##Load Library Pandas

In [20]:
import pandas as pd

##Pandas Operation

In [21]:
list_A = ['a', 'b', 'c', 'd', 'e']
list_A

['a', 'b', 'c', 'd', 'e']

In [22]:
pd_A = pd.Series(list_A)
pd_A

0    a
1    b
2    c
3    d
4    e
dtype: object

In [34]:
data = {
    'Nama' : ['Ali', 'Masya', 'Roni', 'Cika', 'Deny'],
    'Usia' : [22, 21, 18, 25, 30],
    'Asal' : ['Jakarta', 'Bandung', 'Jakarta', 'Bogor', 'Bogor'],
    'Pekerjaan' : ['Swasta', 'Swasta', 'Swasta', 'Karyawan', 'Karyawan']
}

In [35]:
df = pd.DataFrame(data)

In [36]:
df

    Nama  Usia     Asal Pekerjaan
0    Ali    22  Jakarta    Swasta
1  Masya    21  Bandung    Swasta
2   Roni    18  Jakarta    Swasta
3   Cika    25    Bogor  Karyawan
4   Deny    30    Bogor  Karyawan

In [37]:
#Perusahaan hanya ingin tahun, nama, dan asal
df[['Nama', 'Pekerjaan']]

    Nama Pekerjaan
0    Ali    Swasta
1  Masya    Swasta
2   Roni    Swasta
3   Cika  Karyawan
4   Deny  Karyawan

In [43]:
#Perusahaan hanya ingin pekerja dengan usia dibawah 25
df[(df['Usia'] < 25) & (df['Asal'] == 'Jakarta')]

   Nama  Usia     Asal Pekerjaan
0   Ali    22  Jakarta    Swasta
2  Roni    18  Jakarta    Swasta

In [44]:
#Kasus Perkuliahan
data = {
    'Nama' : ['Ali', 'Masya', 'Roni', 'Cika', 'Deny'],
    'Usia' : [20, 22, 23, 20, 19],
    'Nilai' : [75, 90, 92, 76, 60]
}

In [48]:
df = pd.DataFrame(data)

In [59]:
#Mencari data deskriptif
df.describe()

            Usia      Nilai
count   5.000000   5.000000
mean   20.800000  78.600000
std     1.643168  12.992305
min    19.000000  60.000000
25%    20.000000  75.000000
50%    20.000000  76.000000
75%    22.000000  90.000000
max    23.000000  92.000000